<?php $this->layout('home', ['title' => 'Accumulate']) ?>

<h1>Accumulate</h1>
<h4><a href="https://exercism.org/tracks/php/exercises/accumulate">Tratto da Exercism.io</a></h4>

<form action="accumulate.php" method="post" class="form-horizontal">
    <div class="form-group">
        <div class="col-3 col-sm-12">
            <label class="form-label" for="input-string">Valori (separati da virgole)</label>
        </div>
        <div class="col-9 col-sm-12">
            <input class="form-input" type="text" id="input-string" placeholder="7, 9, -12, 23 ..." name="valori">
        </div>
    </div>
    <div class="form-group">
        <div class="col-3 col-sm-12">
            <label class="form-label" for="ops">Operazioni sulla sequenza</label>
        </div>
        <div class="col-9 col-sm-12">
            <select class="form-select" name="ops">
                <option value="0">Scegli un opzione</option>
                <option value="1">Quadrato</option>
                <option value="2">Cubo</option>
                <option value="3">Radice quadrata</option>
            </select>
        </div>

    </div>
    <div class="form-group">
        <div class="col-3 col-sm-12">
            <label class="form-label" for="pari">Scegli su quali numeri operare</label>
        </div>
        <div class="col-3 col-sm-12">
        <label class="form-checkbox">
            <input type="checkbox"><i class="form-icon"></i> Pari
        </label>
            <label class="form-checkbox">
                <input type="checkbox"><i class="form-icon"></i> Dispari
            </label>
        </div>
    </div>


    <p><input type="submit" value="Calcola"></p>
    <!-- form structure -->
</form>
