<html lang="it">
<head>
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css">
    <meta name="viewport" content="width=device-width, height=device-height, user-scalable=no, user-scalable=0;"/>
    <title><?=$this->e($title)?></title>
</head>
<body>
<div class="container">
<?=$this->section('content')?>
</div>
</body>
</html>
